// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpK-N8yXGgiYM32PQ-rngfUdeaCJ65Oo',
    appId: '1:57376175407:web:039e392098f85ff0e8ddda',
    messagingSenderId: '57376175407',
    projectId: 'bolt-usta-app',
    authDomain: 'bolt-usta-app.firebaseapp.com',
    storageBucket: 'bolt-usta-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpzl217mfKg-wzaAVQS7p4jbZ5s0yxek',
    appId: '1:57376175407:android:37502d21339fe7d5e8ddda',
    messagingSenderId: '57376175407',
    projectId: 'bolt-usta-app',
    storageBucket: 'bolt-usta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADF8ZxorXdykS4e7fagh4Fg6tr-h5X5GE',
    appId: '1:57376175407:ios:8ee037c820d00c90e8ddda',
    messagingSenderId: '57376175407',
    projectId: 'bolt-usta-app',
    storageBucket: 'bolt-usta-app.firebasestorage.app',
    iosBundleId: 'com.example.boltUstaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADF8ZxorXdykS4e7fagh4Fg6tr-h5X5GE',
    appId: '1:57376175407:ios:8ee037c820d00c90e8ddda',
    messagingSenderId: '57376175407',
    projectId: 'bolt-usta-app',
    storageBucket: 'bolt-usta-app.firebasestorage.app',
    iosBundleId: 'com.example.boltUstaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtpK-N8yXGgiYM32PQ-rngfUdeaCJ65Oo',
    appId: '1:57376175407:web:7f008e74afd2ec46e8ddda',
    messagingSenderId: '57376175407',
    projectId: 'bolt-usta-app',
    authDomain: 'bolt-usta-app.firebaseapp.com',
    storageBucket: 'bolt-usta-app.firebasestorage.app',
  );
}
